package com.app.entities;

public enum SpecialityEnum {

	PHYSICIAN, NEUOROSURGEON, GENERAL_SURGEON, CARDIAC_SURGEON, ENT_SPECIALIST, SKIN_EXPERT, ORTHOPEDIC_SURGEON,

	PATHOLOGIST,

	ADMINISTRATION,

	RECEPTIONIST

}
